// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OAuth2AuthorizationRequestResponseType.
const (
	Code OAuth2AuthorizationRequestResponseType = "code"
)

// Defines values for OAuth2ErrorSchemaError.
const (
	InvalidClient        OAuth2ErrorSchemaError = "invalid_client"
	InvalidGrant         OAuth2ErrorSchemaError = "invalid_grant"
	InvalidRequest       OAuth2ErrorSchemaError = "invalid_request"
	InvalidScope         OAuth2ErrorSchemaError = "invalid_scope"
	UnauthorizedClient   OAuth2ErrorSchemaError = "unauthorized_client"
	UnsupportedGrantType OAuth2ErrorSchemaError = "unsupported_grant_type"
)

// Defines values for OAuth2TokenRequestGrantType.
const (
	AuthorizationCode OAuth2TokenRequestGrantType = "authorization_code"
	ClientCredentials OAuth2TokenRequestGrantType = "client_credentials"
	Password          OAuth2TokenRequestGrantType = "password"
	RefreshToken      OAuth2TokenRequestGrantType = "refresh_token"
)

// Defines values for OAuth2TokenResponseTokenType.
const (
	Bearer OAuth2TokenResponseTokenType = "Bearer"
)

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	Name  string   `json:"name"`
	Users []string `json:"users"`
}

// CreateApplicationResponse defines model for CreateApplicationResponse.
type CreateApplicationResponse struct {
	ClientId *string `json:"clientId,omitempty"`
}

// CreateTenantResponse defines model for CreateTenantResponse.
type CreateTenantResponse struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	TenantId  *string    `json:"tenantId,omitempty"`
	Version   *string    `json:"version,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Password string `json:"password"`
}

// ListApplicationUsersResponse defines model for ListApplicationUsersResponse.
type ListApplicationUsersResponse struct {
	NextToken *string   `json:"nextToken,omitempty"`
	Usernames *[]string `json:"usernames,omitempty"`
}

// OAuth2AuthorizationRequest defines model for OAuth2AuthorizationRequest.
type OAuth2AuthorizationRequest struct {
	ClientId     string                                 `json:"client_id"`
	RedirectUri  *string                                `json:"redirect_uri,omitempty"`
	ResponseType OAuth2AuthorizationRequestResponseType `json:"response_type"`
	Scope        *string                                `json:"scope,omitempty"`
}

// OAuth2AuthorizationRequestResponseType defines model for OAuth2AuthorizationRequest.ResponseType.
type OAuth2AuthorizationRequestResponseType string

// OAuth2ErrorSchema defines model for OAuth2ErrorSchema.
type OAuth2ErrorSchema struct {
	Error            OAuth2ErrorSchemaError `json:"error"`
	ErrorDescription *string                `json:"error_description,omitempty"`
	ErrorUri         *string                `json:"error_uri,omitempty"`
}

// OAuth2ErrorSchemaError defines model for OAuth2ErrorSchema.Error.
type OAuth2ErrorSchemaError string

// OAuth2TokenRequest defines model for OAuth2TokenRequest.
type OAuth2TokenRequest struct {
	Code         *string                     `json:"code,omitempty"`
	GrantType    OAuth2TokenRequestGrantType `json:"grant_type"`
	RefreshToken *string                     `json:"refresh_token"`
	Scope        *string                     `json:"scope"`
}

// OAuth2TokenRequestGrantType defines model for OAuth2TokenRequest.GrantType.
type OAuth2TokenRequestGrantType string

// OAuth2TokenResponse defines model for OAuth2TokenResponse.
type OAuth2TokenResponse struct {
	AccessToken  string                       `json:"access_token"`
	ExpiresIn    float32                      `json:"expires_in"`
	RefreshToken *string                      `json:"refresh_token,omitempty"`
	Scope        *string                      `json:"scope,omitempty"`
	TokenType    OAuth2TokenResponseTokenType `json:"token_type"`
}

// OAuth2TokenResponseTokenType defines model for OAuth2TokenResponse.TokenType.
type OAuth2TokenResponseTokenType string

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"newPassword"`
	OldPassword string `json:"oldPassword"`
}

// UserLoginRequest defines model for UserLoginRequest.
type UserLoginRequest struct {
	Password    string  `json:"password"`
	RedirectUri *string `json:"redirectUri,omitempty"`
	Username    string  `json:"username"`
}

// UserLoginResponse defines model for UserLoginResponse.
type UserLoginResponse struct {
	RedirectUrl string `json:"redirectUrl"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Message *string `json:"message,omitempty"`
}

// ConflictError defines model for ConflictError.
type ConflictError struct {
	Message *string `json:"message,omitempty"`
}

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError struct {
	Message *string `json:"message,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message *string `json:"message,omitempty"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Message *string `json:"message,omitempty"`
}

// OAuthErrorBadRequest defines model for OAuthErrorBadRequest.
type OAuthErrorBadRequest = OAuth2ErrorSchema

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Message *string `json:"message,omitempty"`
}

// ListApplicationUsersParams defines parameters for ListApplicationUsers.
type ListApplicationUsersParams struct {
	NextToken  *string `form:"nextToken,omitempty" json:"nextToken,omitempty"`
	MaxResults *int    `form:"maxResults,omitempty" json:"maxResults,omitempty"`
}

// OAuth2AuthorizeFormdataRequestBody defines body for OAuth2Authorize for application/x-www-form-urlencoded ContentType.
type OAuth2AuthorizeFormdataRequestBody = OAuth2AuthorizationRequest

// OAuth2TokenFormdataRequestBody defines body for OAuth2Token for application/x-www-form-urlencoded ContentType.
type OAuth2TokenFormdataRequestBody = OAuth2TokenRequest

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserLoginRequest

// CreateOrUpdateUserJSONRequestBody defines body for CreateOrUpdateUser for application/json ContentType.
type CreateOrUpdateUserJSONRequestBody = CreateUserRequest

// ResetUserPasswordJSONRequestBody defines body for ResetUserPassword for application/json ContentType.
type ResetUserPasswordJSONRequestBody = ResetPasswordRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaWW/bOhb+KwRnHtXajZMC9Zube1MobZYmzm1nisBgxCObiUTqklRsN/B/H5DaLXqJ",
	"p25m0L7JDEl9Z/nOpjzhQMSJ4MC1wv0nLEElgiuwP94TegV/p6D0n1IKaZYCwTVwbR5JkkQsIJoJ3rlX",
	"gps1FUwgJuYpkSIBqVl2UwxKkTGYRz1PAPex0pLxMV4svGJF3N1DoPHCLFFQgWSJuRv3DQ4kMyB44eFj",
	"wcOIBS8MajiBAhQKckQKTZmeID0BFKRSAtdIaaIBidAuSlAilQEYKU6EvGOUAn9ZMc6FRiTVEyHZd6BI",
	"C5SADIWMLWDzHovCIPa5BslJdA3yEeTLwi6wIGXBIDBokAis2qlBey70iUg5fXkvUQkELGRAS/ujKVGI",
	"C41Cg9CgvRikemKhVqR7Fuh/SghxH/+jU/G5k/1VdezlB/b26+zAZpLd8MorXlaFBjxwnb8MMW68M39W",
	"KGZKMT5GQiLGH0nEqL01F9288lgC0TCo8NbU28TJSewC6eFUgbQ7mIZYObfkC0RKMrcIjC6Z8cX+t+zi",
	"4prblsyeC2MWh9sgg4gB1z7dSpvFzUPghOs1l9pddGCVkukX9zElGl5pZrG3BbZXZjjKE6nRv2PzI0jF",
	"MifZGvONArnSVAlRairkCi3UdV/udOn9E1O6pnXzSrVaSxxmeigegK90EmPo5zpKC1RG10FOv2WXJZQy",
	"s0Siyxq4kEQKPKerjBh1ApFAmYRAj1LJmkaUzGXDojQYZX95wsDT2Gg4EBRq2q1OqEAksNlCzYu9Guzb",
	"ldqpB7OWnaCIVwXCPDKMivjmlSvZu2oLY0ns77QW/6pdKVdpkgipId9ZYC6OZyK7lGFBjRqh7WnVrtwi",
	"69WWSblaRdZTVxLIGs2FoCZWTYOk7o0je9irqGWAhRLUZKQtPUobBhKoid0kUk6lNI8ZiqVRRO4iwH0t",
	"U1jnUxt2LimrJtVGjVX0fwbXSBCAUpUgMCNxYtBhmJ9O7j4E7IKd+jff/TfnzFc+vzoKjv23/kPy9a/j",
	"03evYX76nX7x2QXzZ2f3Z93z4b96F388TH02ZXfxif73td38SD4cjq8+vIvMOvly0vXvxex8+OfB2f3Z",
	"0dkf/jz8/Po6jD7Oplen12fw8ePJwefhYThNzuA07L29vHh4Oz/9a0ToZ6WmR4GL5jBLmAQ1Yk0xet1u",
	"uZmn8R1Ip/0qsYmiY84IZfygdx8SoWjIlSAhJ5F6oDwUB7xHQhbyh4PePSdTZ5JZFUE8bN/YctP3QCRI",
	"h6stuUPDWo3LGgpwucoVKNCXueevLiVgerk6RXlYRPRy6xRW3+w1rnYBNEnskxizHZNGsg52kTNunAGq",
	"yoGbZSp3euszdE2anXhZIY62yUTV5jYY448QpJLpuc082QvurMuZ+FH9OilS6emXIc6LUXNT9tfK0Sda",
	"J1nJa6raosImga6qUTzgSnA0iCIibaewVBxf+igUEsWEk7Gpg7OyTHnIFpseIpyiWq2uzMuZtgzNikJ0",
	"Zo5CbJrVwaWPa8UafvO6+7pr3TUBThKG+7hnl4zR9MTK34mMdczTGCzusmc0tSG2trs01b/XHC4cdLtL",
	"LYWGme5MdBw1e4mNDcLFg1ldeLgjTJrqlIm7BmrphA33qFFiId8ELqOGrOH1lgRpVmWZOJZf7wWdr2mO",
	"Zq+m0+krU1y9SmUE3ORO+tzezVkMZkI3lNrrHrSlvU5ttMMengCheSfzSWT42tuPbeouekHjU43kj/Lk",
	"X8FfXzhakIeZsV2Clvg7zh7YHn6z62GTKMhYGW4PrBLQseBaigjf1hymzF6JUKu9xVYH23nJMM8rP9FD",
	"GtWewzPadPtv5wnNasnBy8Lv/oftn0fLuu2b9qy3z3iPKnW26at1GqZRHumRbd3zCd1Wal6e6m6r4fZE",
	"yJ7sbT65NOq0xw43H2tO8BYePtpGPNeUsp66cf9bM2l/u13celilcUzkvDQ5IojDNFcyrjtL54nRRaeR",
	"Uze4T23CYDOnJDFoG4e/PWGTO202NaVdlvIZxfW6JOtvWgmxDLC32waaXVzSMTdbNMsmA2+xd2q4ZmOu",
	"YWG1DeVDLaRKzkTz3yzZB0tqxt1Alc5T7ZdPF51ytOquHh3zuX1QyHNe0oC6031/pyDn1YXVAHGHwzGZ",
	"XYFKI60ap2MyY7Hpft90ay064xrGpkfPosOeqLl2fLo2e0VzJEFLBo9As1blNzN/EDONUeqMLNS7Ay87",
	"T0WbvrA5LnVQdECpsftQ7DnL7YuizftqY4lnJuAGxQ7bXYRRUiMVIUJp9sW1ET5/s+CHsGBAs7jS0m+L",
	"BuX8wl3C2QHG/1HZ1hr//eRyrT2wcyQCuwHJcsdLOP3R16+7++E2XWXmXlsH0qyiupA3Cc2/fv68MLp7",
	"2NtX31H/+ruVB68KuUUXICRKrWZ/uYbgsPtu86nmP1X97DaiNA4iNmrjzTwyKKoPMavjt/1eYzyh9gnl",
	"F2SV87PVrsQ6FzbiGVC/65UfQwRrn6xiKb+HLRaLxX8CAAD//5BWkBShKQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
