openapi: 3.0.0
info:
  title: users-service
  version: "0.1.0"
paths:
  /users:
    post:
      tags:
        - Access Control
      description: Create a user object
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequestDto"
      responses:
        201:
          $ref: "#/components/responses/CreateUserResponseDto"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/UnAuthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        409:
          $ref: "#/components/responses/Conflict"
        5XX:
          $ref: "#/components/responses/InternalServerError"
  /users/login:
    post:
      tags:
        - Access Control
      description: Login in entity - returns token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequestDto"
      responses:
        200:
          description: Login response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/UnAuthorized"
        5XX:
          $ref: "#/components/responses/InternalServerError"
  /users/resetPassword:
    post:
      tags:
        - Access Control
      description: Reset password for user - returns token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetUserPasswordDto"
      responses:
        200:
          description: Login response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/UnAuthorized"
  /oauth/token:
    post:
      operationId: OAuth2Token
      tags:
        - Access Control
      description: OAuth2 Token Implementation
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/OAuth2TokenRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OAuth2TokenResponse"
        400:
          $ref: "#/components/responses/OAuthErrorBadRequest"
        401:
          $ref: "#/components/responses/OAuthErrorBadRequest"
  /oauth/authorization:
    get:
      operationId: OAuth2Authorization
      tags:
      - Access Control
      description: OAuth2 Authorization Implementation
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/OAuth2AuthorizationRequest"
      responses:
        302:
          description: Success
          headers:
            Location:
              description: Client requesting authorization code
              schema:
                type: string
                format: uri
        400:
          $ref: "#/components/responses/OAuthErrorBadRequest"
        401:
          $ref: "#/components/responses/OAuthErrorBadRequest"

components:
  schemas:
    OAuth2AuthorizationRequest:
      type: object
      additionalProperties: false
      properties:
        response_type:
          type: string
          enum:
          - code
        scope:
          type: string
        client_id:
          type: string
        redirect_uri:
          type: string
          format: uri
      required:
        - response_type
        - client_id
    ResetUserPasswordDto:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
          pattern: ^[a-zA-Z0-9]+$
        oldPassword:
          type: string
          minLength: 8
        newPassword:
          type: string
          minLength: 8
      required:
        - username
        - oldPassword
        - newPassword
    CreateUserRequestDto:
      type: object
      additionalProperties: false
      properties:
        username:
          type: string
          pattern: ^[a-zA-Z0-9]+$
        password:
          type: string
          minLength: 8
      required:
        - username
        - password
    OAuth2TokenResponse:
      type: object
      additionalProperties: false
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        token_type:
          type: string
          enum:
          - Bearer
        expires_in:
          type: number
          example: 300
        refresh_token:
          type: string
          example: asdgniadin23jfaosdfnsoafnalskdnfo2n3afifnk23jnawe
        scope:
          type: string
      required:
        - access_token
        - token_type
        - expires_in
    LoginResponse:
      type: object
      additionalProperties: false
      properties:
        userId:
          type: string
        token:
          type: string
      required:
        - userId
        - token
    OAuth2TokenRequest:
      type: object
      properties:
        grant_type:
          type: string
          enum:
          - authorization_code
          - password
          - refresh_token
          - client_credentials
        code:
          type: string
        scope:
          type: string
          nullable: true
        refresh_token:
          type: string
          nullable: true
      required:
        - grant_type
    OAuth2ErrorSchema:
      type: object
      properties:
        error:
          type: string
          enum:
            - invalid_request
            - invalid_client
            - invalid_grant
            - unauthorized_client
            - unsupported_grant_type
            - invalid_scope
        error_description:
          type: string
        error_uri:
          type: string
      required:
      - error
  responses:
    CreateUserResponseDto:
      description: ""
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            description: User created
            properties:
              id:
                type: string
            required:
              - id
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    Conflict:
      description: Resource conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    OAuthErrorBadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OAuth2ErrorSchema"
    UnAuthorized:
      description: Not Authorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT